config/routes.rb
Rails.application.routes.draw do
  resources :boards, except: %i[index] do
    resources :pins do 
      resources :comments
    end
  end

  resources :likes, only: [:create, :destroy]

  resources :rooms do
    resources :messages
  end
  get '/inbox', to: 'rooms#index', as: 'inbox'
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  
  root 'pages#home'
  get 'user/:id/profile', to: 'pages#profile', as: 'profile'
  get 'feed', to: 'pages#feed', as: 'feed'
  get '/home', to: 'pages#home', as: 'home'
  get '/notifications', to: 'pages#notifications', as: 'notifications'

  get '/:id/followers', to: 'members#followers', as: 'followers'
  get '/:id/following', to: 'members#following', as: 'following'
  get 'edit_description/:id', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'
  get '/follow/notifications', to: 'members#notification_reqs', as: 'request_notification'
  get '/foryou', to: 'members#foryou', as: 'foryou'

  post 'followability/:id/follow', to: 'followability#follow', as: 'follow'
  post 'followability/:id/unfollow', to: 'followability#unfollow', as: 'unfollow'
  post 'followability/:id/accept', to: 'followability#accept', as: 'accept'
  post 'followability/:id/decline', to: 'followability#decline', as: 'decline'
  post 'followability/:id/cancel', to: 'followability#cancel', as: 'cancel'

  get '/dashboard', to: 'admin#dashboard', as: 'admin'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/admin/dashboard.html.erb
<div class="container">
  <div id="content">
    <div class="container-fluid">
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 text-muted">Dashboard 
          <br>
          <small class="h6 fw-light"><%= current_user.email %></small>
        </h1>
        <div class="user_details">
          <%= image_tag(user_image(current_user), size: '50x50', class: 'rounded-circle')%>
        </div>
      </div>
      <hr>
      <div class="row mt-5">
        <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    Board Count</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= current_user.boards.count %></div>
                </div>
                <div class="col-auto">
                  <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                    Pins Count</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= current_user.pins.count %></div>
                </div>
                <div class="col-auto">
                  <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                    Followers </div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= current_user.followers.count %></div>
                </div>
                <div class="col-auto">
                  <i class="fas fa-comments fa-2x text-gray-300"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                    Following</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800"><%= current_user.following.count%></div>
                </div>
                <div class="col-auto">
                  <i class="fas fa-comments fa-2x text-gray-300"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row mt-5 mb-5">
        <div class="col-lg-6">
          <div class="card p-3">
            <p class="text-muted">Board(In Linechart)</p>
            <%= line_chart current_user.boards.group_by_day(:created_at, range: 1.week.ago...Time.now).count %>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="card p-3">
            <p class="text-muted">Boards(In Piechart)</p>
            <%= pie_chart current_user.boards.group_by_day(:created_at, range: 1.week.ago...Time.now).count %>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <h4 class="card-title">Boards 
            </h4>
            <div class="new_board">
              <%= link_to new_board_path, data: { controller: 'bs-modal'}  do%>
                <i class="bi bi-plus-circle h2 text-secondary"></i>
              <% end %>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th> Cover </th>
                  <th> Board Name </th>
                  <th> Pins Count </th>
                  <th> Created At </th>
                  <th> Actions </th>
                </tr>
              </thead>
              <tbody>
                <% current_user.boards.each do |board| %>
                  <tr>
                    <td><%= image_tag(user_image(board), size: '35x35', class: 'rounded-circle') %></td>
                    <td><%= board.name %></td>
                    <td>
                      <%= board.pins.count %>
                    </td>
                    <td><%= time_ago_in_words(board.created_at) + ' ago'%> </td>
                    <td>
                      <div class="d-flex gap-2">
                        <%= link_to board_path(board), class: 'btn btn-primary' do %>
                          <i class="bi bi-eye-fill"></i>
                        <% end %>
                        <%= button_to  board_path(board), class: 'btn btn-danger', method: :delete, data: { turbo_confirm: 'You sure? '}  do%>
                          <i class="bi bi-trash"></i>
                        <% end %>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="card mt-5">
        <div class="card-body">
          <h4 class="card-title">Pins 
          </h4>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th> Cover </th>
                  <th> Pin Name </th>
                  <th> Board Name </th>
                  <th> Likes Count </th>
                  <th> Comments Count </th>
                  <th> Created At </th>
                  <th> Actions </th>
                </tr>
              </thead>
              <tbody>
                <% current_user.boards.each do |board| %>
                  <% board.pins.each do |pin| %>
                    <tr>
                      <td><%= image_tag(user_image(pin), size: '35x35', class: 'rounded-circle') %></td>
                      <td><%= pin.name %></td>
                      <td><%= pin.board.name %>
                        <i class="<%= pin.board.isPrivate? ? 'bi bi-lock' : 'bi bi-globe' %>"></i>
                      </td>
                      <td>
                        <%= pin.likes.count %>
                      </td>
                      <td>
                        <%= pin.comments.count %>
                      </td>
                      <td><%= time_ago_in_words(pin.created_at) + ' ago'%> </td>
                      <td>
                        <div class="d-flex gap-2">
                          <%= link_to board_pin_path(pin.board_id, pin), class: 'btn btn-primary' do %>
                            <i class="bi bi-eye-fill"></i>
                          <% end %>
                          <%= link_to edit_board_pin_path(board, pin),class: ' btn btn-success', data: { controller: 'bs-modal'} do %>
                            <i class="bi bi-pen"></i>
                          <% end %>
                          <%= button_to [pin.board, pin], class: 'btn btn-danger',method: :delete, data: {'turbo-method': :delete, turbo_confirm: 'You sure?', action: 'click->bootstrap#submitEnd'} do %>
                            <i class="bi bi-trash"></i>
                          <% end %>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="row mt-5 mb-5">
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <h6 class="card-title">Latest Followers</h6>
            </div>
            <div class="card-body">
              <% current_user.followers.each do |followers| %>
                <ul class="users-list clearfix">
                  <div class="d-flex gap-2">
                    <div class="user_image">
                      <%= image_tag(user_image(followers), size: '50x50', class: 'rounded-circle') %>
                    </div>
                    <div class="details d-flex flex-column">
                      <span class="users-list-name" ><b><%= followers.email%></b></span>
                      <small>Joined <%= time_ago_in_words(followers.created_at)+ ' ago' %> </small>
                    </div>
                  </div>
                </ul>
                <hr>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <h6 class="card-title">Latest Following</h6>
            </div>
            <div class="card-body">
              <% current_user.following.each do |followers| %>
                <ul class="users-list clearfix">
                  <div class="d-flex gap-2">
                    <div class="user_image">
                      <%= image_tag(user_image(followers), size: '50x50', class: 'rounded-circle') %>
                    </div>
                    <div class="details d-flex flex-column">
                      <span class="users-list-name" ><b><%= followers.email%></b></span>
                      <small>Joined <%= time_ago_in_words(followers.created_at)+ ' ago' %> </small>
                    </div>
                  </div>
                </ul>
                <hr>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>