config/routes.rb
Rails.application.routes.draw do
  resources :boards, except: %i[index] do
    resources :pins do 
      resources :comments
    end
  end

  resources :likes, only: [:create, :destroy]

  resources :rooms do
    resources :messages
  end
  get '/inbox', to: 'rooms#index', as: 'inbox'
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  
  root 'pages#home'
  get 'user/:id/profile', to: 'pages#profile', as: 'profile'
  get 'feed', to: 'pages#feed', as: 'feed'
  get '/home', to: 'pages#home', as: 'home'
  get '/notifications', to: 'pages#notifications', as: 'notifications'

  get '/:id/followers', to: 'members#followers', as: 'followers'
  get '/:id/following', to: 'members#following', as: 'following'
  get 'edit_description/:id', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'
  get '/follow/notifications', to: 'members#notification_reqs', as: 'request_notification'
  get '/foryou', to: 'members#foryou', as: 'foryou'

  post 'followability/:id/follow', to: 'followability#follow', as: 'follow'
  post 'followability/:id/unfollow', to: 'followability#unfollow', as: 'unfollow'
  post 'followability/:id/accept', to: 'followability#accept', as: 'accept'
  post 'followability/:id/decline', to: 'followability#decline', as: 'decline'
  post 'followability/:id/cancel', to: 'followability#cancel', as: 'cancel'

  get '/dashboard', to: 'admin#dashboard', as: 'admin'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/partials/_bottom_flash.html.erb
<div class="btn-flash" id="btn-flash">
  <small id="btn-flash-msg"></small>
</div>

app/views/partials/_dropdown.html.erb
<% items = [
["Feed", feed_path],
["For You", foryou_path]
]%>
<div class="d-flex justify-content-end p-1 mx-5">
  <%= select_tag "Select", options_for_select(items, request.path), onchange: "Turbo.visit(this.selectedOptions[0].value)", class: 'custom-dropdown' %>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove" >
    <%= message %>
  </div>
<% end %>

app/views/partials/_form_modal.html.erb
<%= turbo_frame_tag "remote_modal", target: '_top' do %>
  <div class="modal fade " id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" data-controller="bootstrap">
    <div class="modal-dialog modal-xl  modal-dialog-centered">
      <div class="modal-content">
        <button type="button" class="btn-close mt-3 mx-3" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <%= render form_partial %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/partials/_image.html.erb
<div data-controller="preview">
  <div class="d-flex gap-5">
    <% if board.image.attached? %>
      <div class="d-flex flex-column gap-4">
        <%= image_tag(board.image, width: '100px', height: '100px')%>
        <%= image_tag '', data: { preview_target: "preview" }, class: "image" %>
      </div>
    <% else %>
      <%= image_tag '', data: { preview_target: "preview" }, class: "image" %>
    <% end %>
    <div class="new_img_box d-flex justify-content-center align-item-center">
      <%= form.label :image, class: 'form-control board_image_label'  %>
      <%= form.file_field :image,
          data: {preview_target: "input", action: "change->preview#preview"}, class: 'board_input'%>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<div id="user-id" class="d-none"><%= user_signed_in? ?  current_user.id : '' %></div>
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
        <%= image_tag('assets/logo.png', class:"bi me-2", size: '35x35')%>
      </a>
      <ul class="nav col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li>
          <%= link_to 'Home', feed_path, class: 'nav-link px-2 link-body-emphasis' %>
        </li>
        <li>
          <%= link_to 'Create', new_board_path, class: 'nav-link px-2 link-body-emphasis' %>
        </li>
      </ul>
      <% if user_signed_in? %>
        <ul class="nav nav-pills gap-4 mx-4">
          <li class="nav-item">
            <%= link_to inbox_path, class: 'position-relative white' do%>
              <i class="bi h4 text-dark  <%= active_link("rooms", "bi-chat-left-text-fill", "bi-chat-left-text") %>  "></i>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="message_count_<%= current_user.id %>">
                <%= current_user.messages.count %>
              </span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to notifications_path, class: 'position-relative white', data: { controller: 'bs-modal'} do%>
              <i class="bi h4 text-dark <%= active_link("pages", " bi-bell-fill", " bi-bell", "notifications") %> "></i>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="notification_count_<%= current_user.id%>">
                <%= current_user.notifications.count %>
              </span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to request_notification_path, class: 'position-relative', data: { controller: 'bs-modal' } do%>
              <i class="bi <%= active_link("members", " bi-people-fill", "bi-people", "notification_reqs") %> </i> h4 text-dark"></i>
              <span class="position-absolute left-0 start-100 translate-middle badge rounded-pill bg-danger"  id="follow_count_<%= current_user.id%>">
                <%= connection_notifications %>
                <span class="visually-hidden">unread messages</span>
              </span>
            <% end %>
          </li>
        </ul>
        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag(user_image(current_user), alt: "github-profile", width:"32", height:"32", class: "rounded-circle") %>
          </a>
          <ul class="dropdown-menu text-small" style="">
            <li>
              <%= link_to 'Profile', profile_path(current_user), class: 'dropdown-item' %>
            </li>
            <li>
              <%= link_to 'Dashboard', admin_path, class: 'dropdown-item' %>
            </li>
            <li>
              <%= link_to 'Settings', edit_user_registration_path(current_user),class: "dropdown-item" %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to 'Logout', destroy_user_session_path	,method: :delete, data: { turbo_confirm: "#{current_user.email } will be logged out."  }, class: 'dropdown-item text-danger' %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/partials/_return_home.html.erb
<div class="position-absolute right-15 p-2 ">
  <%= link_to :back, class: 'text-decoration-none' do %>
    <i class="bi bi-caret-left-fill h3-d-flex justify-content-center align-items-center"></i> Return back
  <% end %>
</div>

app/views/partials/_user.html.erb
<div id="<%= dom_id(user) %>">
  <div class="d-flex flex-column align-items-center">
    <%= image_tag(user_image(user), alt: "PP", width:"42", height:"42", class: "rounded-circle") %><span class="dot"></span>
    <small class="fw-light"><%= user.name %></small>
  </div>
</div>