config/routes.rb
Rails.application.routes.draw do
  resources :boards, except: %i[index] do
    resources :pins do 
      resources :comments
    end
  end

  resources :likes, only: [:create, :destroy]

  resources :rooms do
    resources :messages
  end
  get '/inbox', to: 'rooms#index', as: 'inbox'
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  
  root 'pages#home'
  get 'user/:id/profile', to: 'pages#profile', as: 'profile'
  get 'feed', to: 'pages#feed', as: 'feed'
  get '/home', to: 'pages#home', as: 'home'
  get '/notifications', to: 'pages#notifications', as: 'notifications'

  get '/:id/followers', to: 'members#followers', as: 'followers'
  get '/:id/following', to: 'members#following', as: 'following'
  get 'edit_description/:id', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'
  get '/follow/notifications', to: 'members#notification_reqs', as: 'request_notification'
  get '/foryou', to: 'members#foryou', as: 'foryou'

  post 'followability/:id/follow', to: 'followability#follow', as: 'follow'
  post 'followability/:id/unfollow', to: 'followability#unfollow', as: 'unfollow'
  post 'followability/:id/accept', to: 'followability#accept', as: 'accept'
  post 'followability/:id/decline', to: 'followability#decline', as: 'decline'
  post 'followability/:id/cancel', to: 'followability#cancel', as: 'cancel'

  get '/dashboard', to: 'admin#dashboard', as: 'admin'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/room.rb
class Room < ApplicationRecord
  after_create_commit { broadcast_prepend_to "rooms" }
  after_update_commit { broadcast_update_to "rooms" }
  after_destroy_commit { broadcast_remove_to "rooms" }
  
  has_many :messages, dependent: :destroy

  belongs_to :user
  
  validates :name, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :index_params, only: %i[index show]
  before_action :user_for_broadcast, only: %i[index show create update]
  before_action :verify_correct_user, only: %i[edit update destroy]

  def index
  end

  def show
    @messages = @room.messages.all.order('Created_at Asc')
    @message = Message.new
  
    render 'index'
  end

  def new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)
  
    respond_to do |format|
      if @room.save
        format.turbo_stream { flash.now[:notice] = "Room added successfully." }
      else
        format.html { redirect_to inbox_path, notice: "Room name can't be blank" }
      end
    end
  end

  def update
  
    respond_to do |format|
      if @room.update(room_params)
        ActionCable.server.broadcast 'room_channel', {room_id: @room.id, room_name: @room.name }
        format.turbo_stream { flash.now[:notice] = "Room has been updated." }        
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy!
    respond_to do |format|
        format.turbo_stream {flash.now[:notice] = "Room destroyed successfully." }

    end
  end

  private

    def index_params 
      @rooms = Room.order("Created_at Desc")
      @new_room = Room.new
      user_online = Kredis.unique_list "users_online"
      @users = User.find(user_online.elements)
    end
    
    def set_room
      @room = Room.find(params[:id])
    end

    def user_for_broadcast
      @now_user = current_user.id
    end

    def verify_correct_user
      @room = current_user.rooms.find_by(id: params[:id])
      redirect_to root_path,alert: "Only the admin of this room can access this!" if @room.nil?
    end

    def room_params
      params.require(:room).permit(:name, :user_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <div>
    <%= form.text_field :name, class:'form-control' %>
    <%= form.hidden_field :user_id, value: current_user.id, id: 'room_user_id',  class:'form-control' %>
  </div>
  <div>
    <%= form.submit class: 'btn btn-dark w-100 mt-2 btn-sm'%>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<%= turbo_frame_tag room do %>
  <p class="p-2 text-center btn-lg bg-primary rounded text-white">
    <%= link_to room.name, room, class: 'text-white text-decoration-none', data: {turbo_frame: '_top'} %>
  </p>
  <% if @now_user == room.user.id %>
    <%= render 'rooms/room_actions', room: room %>
  <% end %>
  <hr>
<% end %>

app/views/rooms/_room_actions.html.erb
<div class="d-flex gap-2 justify-content-center">
  <button type='button' class= 'btn btn-sm btn-danger' data-controller= 'delete-modal' data-action="click->delete-modal#click">
    <i class="bi bi-trash3"></i>
  <button>
  <%= link_to edit_room_path(room), class: 'btn btn-success btn-sm w-100' do%>
    <i class="bi bi-pen"></i>
  <% end %>
</div>

<!-- Bootstrap Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this room?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <!-- delete logic -->
        <%= button_to "Delete", room_path(room), method: :delete, class: "btn btn-danger", data: { 'bs-dismiss': "modal" } %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/create.turbo_stream.erb
<%= turbo_stream.prepend "rooms" do %>
  <%= render 'rooms/room', room: @room %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/rooms/destroy.turbo_stream.erb
<%= turbo_stream.remove @room %>
<%= render_turbo_stream_flash_messages %>

app/views/rooms/edit.html.erb
<div class="container">
  <%= turbo_frame_tag @room do %>
    <%= render "form", room: @room %>
  <% end %>
</div>

app/views/rooms/index.html.erb
<% content_for(:html_title) { "Rooms | " } %>
<%= turbo_stream_from "online_users", channel: OnlineChannel %>
<div class="row p-4">
  <div class="col-lg-2 col-border ">
    <div class="user_details">
      <p class="fw-light">Logged in as: <br>
        <span class="fw-bold"><%= current_user.email %></span>
      </p>
    </div>
    <hr>
    <p class="text-center">Users Online <i class="bi bi-person-circle"></i> </p>
    <div id="users-list" class="d-flex gap-2" style="overflow-x: scroll;">
      <% @users.each do |user| %>
        <%= render 'partials/user', user: user %>
      <% end %>
    </div>
    <hr>
    <div id="new-room">
      <%= render 'rooms/form', room: @new_room %>
    </div>
    <hr>
    <p class="text-center ">Rooms</p>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms">
      <% @rooms.each do |room| %>
        <%= render room %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-10">
    <% if @room %>
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex flex-column">
          <h3 class="fw-bold display-6" id="<%= dom_id(@room, 'name') %>">
            <%= @room.name %>
          </h3>
          <small class="h6 fw-light"><i class="bi bi-person-fill h6"></i><%= @room.user.email %></small>
        </div>
        <br>
        <p class="text-muted fw-normal">
          <i class="bi bi-alarm"></i>  Created <%= time_ago_in_words(@room.created_at) + ' ago' %>
          <br>
          <i class="bi bi-chat"></i> <b><%= pluralize(@room.messages.count, 'message') %> </b>
        </p>
      </div>
      <hr>
      <%= turbo_stream_from @room %>
      <div id="messages" data-scroll-target="container" data-controller="scroll" >
        <% @messages.each do |message| %>
          <%= render 'messages/message', message: message %>
        <% end %>
      </div>
      <div class="msg_form">
        <%= render 'messages/form'%>
      </div>
    <% else %>
      <div class="container d-flex justify-content-center align-items-center flex-column" style="height: 80vh;">
        <i class="bi bi-plus-square-dotted display-1 text-muted"></i>
        <h1 class="text-muted fw-bold mt-4">Join a room and get started!</h1>
        <p class="text-muted fw-light">Start your conversation by entering a room.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/rooms/update.turbo_stream.erb
<%= turbo_stream.update @room %>
<%= render_turbo_stream_flash_messages %>