config/routes.rb
Rails.application.routes.draw do
  resources :boards, except: %i[index] do
    resources :pins do 
      resources :comments
    end
  end

  resources :likes, only: [:create, :destroy]

  resources :rooms do
    resources :messages
  end
  get '/inbox', to: 'rooms#index', as: 'inbox'
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  
  root 'pages#home'
  get 'user/:id/profile', to: 'pages#profile', as: 'profile'
  get 'feed', to: 'pages#feed', as: 'feed'
  get '/home', to: 'pages#home', as: 'home'
  get '/notifications', to: 'pages#notifications', as: 'notifications'

  get '/:id/followers', to: 'members#followers', as: 'followers'
  get '/:id/following', to: 'members#following', as: 'following'
  get 'edit_description/:id', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'
  get '/follow/notifications', to: 'members#notification_reqs', as: 'request_notification'
  get '/foryou', to: 'members#foryou', as: 'foryou'

  post 'followability/:id/follow', to: 'followability#follow', as: 'follow'
  post 'followability/:id/unfollow', to: 'followability#unfollow', as: 'unfollow'
  post 'followability/:id/accept', to: 'followability#accept', as: 'accept'
  post 'followability/:id/decline', to: 'followability#decline', as: 'decline'
  post 'followability/:id/cancel', to: 'followability#cancel', as: 'cancel'

  get '/dashboard', to: 'admin#dashboard', as: 'admin'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :verify_user, only: %i[followers following]
  def edit_description; end

  def update_description
          @user = current_user
          respond_to do |format|
          if @user.update(user_personal_info_params)
              format.turbo_stream
          end
      end
  end

  def foryou
    @user = current_user.following.all
  end

  def notification_reqs
  end

  def followers
    @followers = @user.followers.all
  end

  def following
    @following = @user.following.all
  end
  private

  def verify_user
    @user = User.find(params[:id])
  end

  def user_personal_info_params
      params.require(:user).permit(:image, :description)
  end
end

app/views/members/_description_modal.html.erb
<%= form_with model: current_user, url: update_member_description_path, method: :patch do |form|%>
  <div class="model-body">
    <div class="row">
      <div class="col-lg-12">
        <div class="form-group d-flex justify-content-center align-items-center">
          <% if current_user.image.attached? %>
            <%= image_tag(user_image(current_user), size: '50x50', class: 'rounded-circle') %>
          <% end %>
        </div>
        <div class="form-group">
          <%= form.label :Avatar, class: 'mb-2 mt-2 p-1' %>
          <%= form.file_field :image, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= form.label :Description, class: 'mb-2 mt-2 p-1' %>
          <%= form.text_area :description, class: 'form-control', rows: 4, max: 20%>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= form.submit "Save Changes", data: { action: 'click->bootstrap#submitEnd' }, class: 'btn btn-dark w-100'%>
  </div>
<% end %>

app/views/members/_follow_notification.html.erb
<p class="text-center text-muted fw-bold">All activities releted to your connection will pop here!</p>
<div class="row">
  <div >
    <div class="container my-3 p-3 bg-body rounded shadow-sm">
      <h6 class="border-bottom pb-2 mb-0 text-muted">Recent Requests</h6>
      <% current_user.follow_requests.each do |request| %>
        <div class="d-flex justify-content-between text-body-secondary pt-3 border-bottom">
          <div class="pb-3 mb-0 small lh-sm">
            <strong class="text-gray-dark"><%= link_to request.followerable.email, profile_path(request.followerable.id) %></strong>
            requested to follow you. <small class="fw-light">(<%= time_ago_in_words(request.created_at)+ ' ago' %>)</small>
          </div>
          <div class="req_actions d-flex mb-2">
            <%= button_to "Accept", accept_path(request.followerable), class:'btn btn-primary btn-sm' %>
            <%= button_to "Decline", decline_path(request.followerable), class:'btn btn-danger mx-1 btn-sm' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div>
    <div class="container my-3 p-3 bg-body rounded shadow-sm">
      <h6 class="border-bottom pb-2 mb-0 text-muted">Recent Followers</h6>
      <% current_user.followers.each do |user| %>
        <div class="d-flex text-body-secondary border-bottom pt-3">
          <p class="pb-3 mb-0 small lh-sm ">
            <strong class="d-flex gap-4 text-gray-dark">
              <%= user.email %>
              <span class="badge text-bg-danger">New</span>
            </strong>
            started following you...
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/members/_followers.html.erb
<% if @followers.present? %>
  <% @followers.each do |user| %>
    <h3 class="text-center text-muted">Followers</h3>
    <%= render 'members/individual_followers', user: user%>
  <% end %>
<% else %>
  <p class="text-center text-muted">No Followers Found!</p>
<% end %>

app/views/members/_following.html.erb
<% if @following.present? %>
  <% @following.each do |user| %>
    <h3 class="text-center text-muted">Following</h3>
    <%= render 'members/individual_followers', user: user%>
  <% end %>
<% else %>
  <p class="text-center text-muted">No Followers Found!</p>
<% end %>

app/views/members/_individual_followers.html.erb
<div class="d-flex gap-2">
  <div class="user_image">
    <%= image_tag(user_image(user), width: "32", height: '32', class: 'rounded-circle')%>
  </div>
  <div class="user_details d-flex flex-column">
    <b><%= link_to user.email, profile_path(user) %></b>
    <small class="text-muted fw-light">
      <%= pluralize(user.pins.count, 'pin') %> | <%= time_ago_in_words(user.created_at) + ' ago'%>
    </small>
  </div>
</div>
<hr>

app/views/members/edit_description.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do%>
  <%= render 'partials/form_modal', form_partial: 'members/description_modal'%>
<% end %>

app/views/members/followers.html.erb
<% content_for(:html_title) { "Followers | " } %>
<%= render 'partials/return_home' %>
<div class="container mt-5">
  <% @followers.each do |user| %>
    <%= render 'members/individual_followers', user: user%>
  <% end %>
</div>

app/views/members/followers.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'partials/form_modal', modal_title: 'Followers', form_partial: 'members/followers' %>
<% end %>

app/views/members/following.html.erb
<% content_for(:html_title) { "Following | " } %>
<%= render 'partials/return_home' %>
<div class="container mt-5">
  <% @following.each do |user| %>
    <%= render 'members/individual_followers', user: user%>
  <% end %>
</div>

app/views/members/following.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'partials/form_modal', modal_title: 'Followers', form_partial: 'members/following' %>
<% end %>

app/views/members/foryou.html.erb
<% content_for(:html_title) { 'For You | ' } %>
<%= render 'partials/dropdown' %>
<% @user.each do |user| %>
  <% if user.pins.present? %>
    <div class="image_container">
      <% user.pins.each do |pin| %>
        <%= render 'pins/pin', pin: pin %>
      <% end %>
    </div>
  <% else %>
    <h3 class="text-center h2 fw-light mt-5 text-muted">
      <p class="h1"><i class="bi bi-pin-fill"></i></p>
      Oops! No Pins Found!
    </h3>
  <% end %>
<% end %>

app/views/members/notification_reqs.html.erb
<% content_for(:html_title) { "(#{current_user.follow_requests.count })  Requests | " } %>
<%= render 'members/follow_notification' %>

app/views/members/notification_reqs.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'partials/form_modal', modal_title: 'Followers', form_partial: 'members/follow_notification' %>
<% end %>

app/views/members/update_description.turbo_stream.erb
<%= turbo_stream.update(dom_id(@user)) do %>
  <%= render 'pages/users_profile', user: @user %>
<% end %>